### ISSUE TITLE
PHP Restructure: RFC to Migrate from Buildpack.yml to Environment Variables

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/php#472]
## Context
Per [PHP RFC 0001](https://github.com/paketo-buildpacks/rfcs/blob/main/text/php/0001-restructure.md) we are restructuring the PHP language family of buildpacks to make them more modular, up-to-date, and as a result, maintainable.

## Issue
As a part of the process of bring the PHP buildpacks up to speed with other Paketo buildpacks, we should migrate from setting configurations via a `buildpack.yml` to using environment variables across all buildpacks, as we have already done in a [number of other buildpacks](https://github.com/paketo-buildpacks/rfcs/issues/58). 

Currently, the `buildpack.yml` file is used to specify:
- PHP versions,
- a user's choice of web-server, 
- an alternative web app code directory to `htdocs`, 
- alternative library code directory to `lib`, 
- scripts, 
- server admin, 
- redis session store service, 
- memcache session store service, and 
- configuring composer

If we are moving away from the `buildpack.yml` pattern, alternatives for all of these options should be explained in the RFC. The [README of the PHP Web buildpack](https://github.com/paketo-buildpacks/php-web#buildpackyml-configurations) contains examples of all of these fields.

## Acceptance
This issue can be closed out when an RFC is added to the [PHP RFCs directory](https://github.com/paketo-buildpacks/rfcs/tree/main/text/php)

**Comment by ForestEckhardt** [comment]
Do we know what purpose the `scripts` field in `buildpack.yml` servers that is not covered by the `Procfile` buildpack?

**Comment by dmikusa-pivotal** [comment]
> Do we know what purpose the `scripts` field in `buildpack.yml` servers that is not covered by the `Procfile` buildpack?

None. I think we should drop a lot of that "scripts" behavior. You can set a Procfile if you want to have a start command baked into the image or you can set the command to run when you run the container. We should just facilitate that PHP is on the PATH.

I think it was largely there because when we originally wrote the PHP CNBs there was a goal of having them be more of a drop-in replacement for the v2 PHP buildpack, which had some functionality for running scripts.

I'm +1 for dropping as much of the scripts functionality as can be accomplished through other buildpacks with the goal of simplifying the PHP buildpacks.

**Comment by dmikusa-pivotal** [comment]
Along a similar line:

> a user's choice of web-server,

This might be able to be done through the build plan instead. Rather than have the user say "give me httpd" or "give me nginx", if those web server providers all contribute "web-server" or something like that. Then a user can specify which one they want by controlling the buildpack order.

For example, you'd have the PHP CNB include HTTPD by default (it tends to be the most popular from what I've seen). A user could override that by using `pack build -b nginx -b php`. Nginx would run first in this case and provide the "web-server" requirement. Since it's already provided, HTTPD would run and no-op.

**Comment by ForestEckhardt** [comment]
> For example, you'd have the PHP CNB include HTTPD by default (it tends to be the most popular from what I've seen). A user could override that by using `pack build -b nginx -b php`. Nginx would run first in this case and provide the "web-server" requirement. Since it's already provided, HTTPD would run and no-op.

Do we think that a valid and usable customer workflow is to tell them to run a "multi-buildpack" build for lack of a better turn of phrase? I am not intimately familiar of what that would need to look like on other platforms (I am thinking Kpack).

I am a little dubious in thinking that we should switch to HTTPD default. I am all for controlling the outcome based on the build plan but I think we could keep `php-server` as the default option. Is there a reason that we should make HTTPD the default that I am unaware of? 

I think an interface like `pack build -b nginx -b php` || `pack build -b httpd -b php` is much more consistent in the long run.

Just to lay this out concretely I think that this is the order grouping I would go for:
```toml
[[order]] # HTTPD web server

  [[order.group]]
    id = "paketo-buildpacks/php-dist"
    version = ""

  [[order.group]]
    id = "paketo-buildpacks/composer"
    version = ""
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/composer-install"
    version = ""
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/php-fpm"
    version = ""

  [[order.group]]
    id = "paketo-buildpacks/php-httpd"
    version = ""

  [[order.group]]
    id = "paketo-buildpacks/php-memcached-session-handler"
    version = ""
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/php-redis-session-handler"
    version = ""
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = ""
    optional = true

[[order]] # Nginx web server

  [[order.group]]
    id = "paketo-buildpacks/php-dist"
    version = ""

  [[order.group]]
    id = "paketo-buildpacks/composer"
    version = ""
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/composer-install"
    version = ""
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/php-fpm"
    version = ""

  [[order.group]]
    id = "paketo-buildpacks/php-nginx"
    version = ""

  [[order.group]]
    id = "paketo-buildpacks/php-memcached-session-handler"
    version = ""
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/php-redis-session-handler"
    version = ""
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = ""
    optional = true

[[order]] # Built-in web server (web), FPM (php-fpm) & Script (Procfile)

  [[order.group]]
    id = "paketo-buildpacks/php-dist"
    version = ""

  [[order.group]]
    id = "paketo-buildpacks/composer"
    version = ""
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/composer-install"
    version = ""
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/php-fpm"
    version = ""

  [[order.group]]
    id = "paketo-buildpacks/php-builtin-server"
    version = ""

  [[order.group]]
    id = "paketo-buildpacks/php-memcached-session-handler"
    version = ""
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/php-redis-session-handler"
    version = ""
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = ""
    optional = true
```
