### ISSUE TITLE
Restructure: Update Language Family Order Groups 

### ISSUE THREAD

**Issue by joshuatcasey** [paketo-buildpacks/php#524]
As per [PHP RFCs](https://github.com/paketo-buildpacks/rfcs/blob/main/text/php) we are restructuring the PHP language family of buildpacks to make them more modular, up-to-date, and as a result, maintainable.

Note: This issue is up to date with the PHP RFCs as of commit [6dc7377](https://github.com/paketo-buildpacks/rfcs/commit/6dc737743adca37c26353fd0a9d479b6dbe9dfd3), and deprecates issues #475 and #483.

## ~~Blocked~~
~~This issue is blocked on the release of all buildpacks listed in the New Buildpacks section below.~~

~~Ensure that https://github.com/paketo-buildpacks/php-dist/issues/376 is done and release for inclusion into this release.~~

## New Buildpacks

This issue is to update the language family order groupings to make use of newly added PHP buildpacks:

- [php-fpm](https://github.com/paketo-buildpacks/php-fpm)
- [php-httpd](https://github.com/paketo-buildpacks/php-httpd)
- [php-nginx](https://github.com/paketo-buildpacks/php-nginx)
- [php-builtin-server](https://github.com/paketo-buildpacks/php-builtin-server)
- [php-memcached-session-handler](https://github.com/paketo-buildpacks/php-memcached-session-handler) (optional = true)
paketo-buildpacks/php-memcached-session-handler#1

- [php-redis-session-handler](https://github.com/paketo-buildpacks/php-redis-session-handler) (optional = true)
paketo-buildpacks/php-redis-session-handler#1

- [composer](https://github.com/paketo-buildpacks/composer) (optional = true)
- [composer-install](https://github.com/paketo-buildpacks/composer-install) (optional = true)
paketo-buildpacks/composer-install#4

- [php-start](https://github.com/paketo-buildpacks/php-start)

In addition:

- Remove unused buildpacks
- Add new integration tests and fixtures as needed
- Update the README accordingly
- **remove buildpack.yml warnings and support from PHP Dist before release**

# Acceptance

## Use cases
With the new language family buildpack, I can successfully:
- [x] Build an image to run HTTPD web server with php
- [x] Build an image to run Nginx web server with php
- [x] Build an image to run Built-in php web server
- [x] Build an image to run FPM process manager
- [x] Build an image to run a PHP CLI script using Procfile.
- [x] Optionally use composer as application level package manager
- [x] Optionally use memcached as session handler
- [x] Optionally use redis as session handler

## Order Groups
As of commit [2f024a5](https://github.com/paketo-buildpacks/php/blob/2f024a5820d5cb91bfae3d290bf03db4a45d0377/buildpack.toml), the PHP buildpack had one single order group. With the PHP RFCs there should be a total of three order groups, shown here in their entirety. 

```toml
[[order]] # HTTPD web server

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/php-dist"
    version = ""

  [[order.group]]
    id = "paketo-buildpacks/composer"
    version = ""
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/composer-install"
    version = ""
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    version = ""

  [[order.group]]
    id = "paketo-buildpacks/php-fpm"
    version = ""

  [[order.group]]
    id = "paketo-buildpacks/php-httpd"
    version = ""

  [[order.group]]
    id = "paketo-buildpacks/php-memcached-session-handler"
    version = ""
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/php-redis-session-handler"
    version = ""
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/php-start"
    version = ""

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = ""


  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true

[[order]] # Nginx web server

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/php-dist"
    version = ""

  [[order.group]]
    id = "paketo-buildpacks/composer"
    version = ""
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/composer-install"
    version = ""
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    version = ""

  [[order.group]]
    id = "paketo-buildpacks/php-fpm"
    version = ""

  [[order.group]]
    id = "paketo-buildpacks/php-nginx"
    version = ""

  [[order.group]]
    id = "paketo-buildpacks/php-memcached-session-handler"
    version = ""
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/php-redis-session-handler"
    version = ""
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/php-start"
    version = ""

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = ""

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true

[[order]] # Built-in web server (web), FPM (php-fpm) & Script (Procfile)

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/php-dist"
    version = ""

  [[order.group]]
    id = "paketo-buildpacks/composer"
    version = ""
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/composer-install"
    version = ""
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/php-fpm"
    version = ""

  [[order.group]]
    id = "paketo-buildpacks/php-builtin-server"
    version = ""

  [[order.group]]
    id = "paketo-buildpacks/php-memcached-session-handler"
    version = ""
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/php-redis-session-handler"
    version = ""
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = ""
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
```
